ignoredBuiltDependencies:
  - better-sqlite3
  - core-js-pure
  - dtrace-provider
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - re2

patchedDependencies:
  parse-packagejson-name@1.1.0: patches/parse-packagejson-name@1.1.0.patch
