ignoredBuiltDependencies:
  - better-sqlite3
  - core-js-pure
  - dtrace-provider
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - re2

overrides:
  '@dword-design/base-config-node': 5.0.0
