module.exports = [
  require('./init'),
  require('./register'),
  require('./unregister'),
  require('./build'),
  require('./start'),
  require('./lint'),
  require('./lint-staged'),
  require('./depcheck'),
  require('./pre-commit'),
  require('./install'),
  require('./add'),
  require('./upgrade'),
  require('./remove'),
  require('./outdated'),
  require('./test'),
  require('./publish'),
]
