#!/usr/bin/env node

const path = require('path')
const readPkgUp = require('read-pkg-up')
const fs = require('fs-extra')
const config = require('./config')

Promise.all([config(), readPkgUp()])
  .then(([config, { path: packagePath }]) => [config, path.dirname(packagePath)])
  .then(([{ gitignore: gitignoreConfig = [] }, rootPath]) =>
    fs.readFile(path.resolve(rootPath, 'src/gitignore'), 'utf8')
      .then(content => fs.writeFile(
        path.resolve(rootPath, 'dist/gitignore'),
        [content, ...gitignoreConfig].join('\r\n'),
      ))
  )
