jobs:
  cancel-existing:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: rokroskar/workflow-run-cleanup-action@v0.2.2
  release:
    if: github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: git config --global user.email "actions@github.com"
      - run: git config --global user.name "GitHub Actions"
      - run: yarn --frozen-lockfile
      - run: yarn clean
      - run: yarn lint
      - env:
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Push changed files
        run: yarn dw-ci push-changed-files
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        name: Release
        run: yarn semantic-release
  test:
    needs: cancel-existing
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: git config --global user.email "actions@github.com"
      - run: git config --global user.name "GitHub Actions"
      - run: yarn --frozen-lockfile
      - run: yarn clean
      - run: yarn test
      - if: matrix.os == 'ubuntu-latest' && matrix.node == 12
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        exclude:
          - node: 10
            os: macos-latest
          - node: 10
            os: windows-latest
        node:
          - 10
          - 12
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
name: build
on:
  push:
    branches:
      - "**"
